// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { HealthAppData, HealthAppResponses, HealthCosData, HealthCosResponses, HealthDbData, HealthDbResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 */
export const healthApp = <ThrowOnError extends boolean = false>(options?: Options<HealthAppData, ThrowOnError>) => (options?.client ?? client).get<HealthAppResponses, unknown, ThrowOnError>({ url: '/api/health', ...options });

/**
 * Health Db
 */
export const healthDb = <ThrowOnError extends boolean = false>(options?: Options<HealthDbData, ThrowOnError>) => (options?.client ?? client).get<HealthDbResponses, unknown, ThrowOnError>({ url: '/api/health/db', ...options });

/**
 * Health Cos
 */
export const healthCos = <ThrowOnError extends boolean = false>(options?: Options<HealthCosData, ThrowOnError>) => (options?.client ?? client).get<HealthCosResponses, unknown, ThrowOnError>({ url: '/api/health/cos', ...options });
