// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HealthStatus
 */
export type HealthStatus = {
    /**
     * Status
     */
    status: 'ok' | 'error' | 'not_configured';
    /**
     * Detail
     */
    detail?: string | null;
};

export type HealthAppData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthAppResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type HealthAppResponse = HealthAppResponses[keyof HealthAppResponses];

export type HealthDbData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/db';
};

export type HealthDbResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type HealthDbResponse = HealthDbResponses[keyof HealthDbResponses];

export type HealthCosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/cos';
};

export type HealthCosResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type HealthCosResponse = HealthCosResponses[keyof HealthCosResponses];
