// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AgentStep
 *
 * Agentic RAG 单轮决策 + 观察快照。
 *
 * plan_retrieval 先填决策字段（round / action / reason / route / query），
 * retrieve 跑完后 observe_context 回填观察字段（retrieved_count / top_score / sufficient）。
 */
export type AgentStep = {
    /**
     * Round
     */
    round: number;
    /**
     * Action
     */
    action: 'initial' | 'proceed' | 'rewrite_query' | 'switch_route' | 'refuse';
    /**
     * Reason
     */
    reason: string;
    /**
     * Route
     */
    route: 'original' | 'rewrite' | 'hyde' | 'multi_query';
    /**
     * Query
     */
    query: string;
    /**
     * Retrieved Count
     */
    retrieved_count?: number | null;
    /**
     * Top Score
     */
    top_score?: number | null;
    /**
     * Sufficient
     */
    sufficient?: boolean | null;
};

/**
 * AssignRolesRequest
 */
export type AssignRolesRequest = {
    /**
     * Role Ids
     */
    role_ids?: Array<string>;
};

/**
 * Body_reindexDocument
 */
export type BodyReindexDocument = {
    /**
     * File
     *
     * 新版本文件（MIME 必须与原文档一致）
     */
    file: Blob | File;
};

/**
 * Body_uploadDocument
 */
export type BodyUploadDocument = {
    /**
     * File
     *
     * 待上传文档（PDF / DOCX / Markdown / HTML）
     */
    file: Blob | File;
    /**
     * Permission Tags
     *
     * JSON 数组字符串，例如 ["public","hr"]；空 / 不传视为公开
     */
    permission_tags?: string | null;
};

/**
 * ChatRequest
 */
export type ChatRequest = {
    /**
     * Question
     */
    question: string;
};

/**
 * CitationRead
 *
 * assistant 消息引用的 chunk 快照。
 *
 * document_id / chunk_id 可能为空（原文档 / chunk 已被删除）。
 */
export type CitationRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Ordinal
     */
    ordinal: number;
    /**
     * Document Id
     */
    document_id?: string | null;
    /**
     * Chunk Id
     */
    chunk_id?: string | null;
    /**
     * Document Name
     */
    document_name: string;
    /**
     * Page No
     */
    page_no?: number | null;
    /**
     * Quote
     */
    quote: string;
    retrieval_meta?: RetrievalMeta | null;
};

/**
 * ConversationCreate
 */
export type ConversationCreate = {
    /**
     * Title
     */
    title?: string;
};

/**
 * ConversationDetail
 *
 * 会话详情：会话本身 + 历史消息（含引用）。
 */
export type ConversationDetail = {
    conversation: ConversationRead;
    /**
     * Messages
     */
    messages: Array<MessageRead>;
};

/**
 * ConversationListItem
 *
 * 会话列表元素：侧栏渲染用，比 ConversationRead 多带 message_count。
 */
export type ConversationListItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Message Count
     */
    message_count: number;
};

/**
 * ConversationPage
 *
 * 会话列表分页响应。统一 page/page_size 风格，与第 3 章文档列表一致。
 */
export type ConversationPage = {
    /**
     * Items
     */
    items: Array<ConversationListItem>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * ConversationRead
 */
export type ConversationRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DatasetInfo
 */
export type DatasetInfo = {
    /**
     * Name
     */
    name: string;
    /**
     * Size
     */
    size: number;
};

/**
 * DatasetListResponse
 */
export type DatasetListResponse = {
    /**
     * Items
     */
    items: Array<DatasetInfo>;
};

/**
 * DocumentChunkDetail
 *
 * chunk 详情：返回完整 content。
 */
export type DocumentChunkDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Chunk Index
     */
    chunk_index: number;
    /**
     * Page No
     */
    page_no?: number | null;
    /**
     * Section Path
     */
    section_path?: string | null;
    /**
     * Content
     */
    content: string;
    /**
     * Char Count
     */
    char_count: number;
    /**
     * Chunk Hash
     */
    chunk_hash: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * DocumentChunkListResponse
 */
export type DocumentChunkListResponse = {
    /**
     * Items
     */
    items: Array<DocumentChunkRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
    stats?: DocumentChunkStats | null;
};

/**
 * DocumentChunkRead
 *
 * chunk 列表项。content_excerpt 已在 API 层截断到固定长度。
 */
export type DocumentChunkRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Chunk Index
     */
    chunk_index: number;
    /**
     * Page No
     */
    page_no?: number | null;
    /**
     * Section Path
     */
    section_path?: string | null;
    /**
     * Content Excerpt
     */
    content_excerpt: string;
    /**
     * Char Count
     */
    char_count: number;
    /**
     * Chunk Hash
     */
    chunk_hash: string;
};

/**
 * DocumentChunkStats
 *
 * 切分统计：直观看到 chunk_size / overlap 配置的实际效果。
 */
export type DocumentChunkStats = {
    /**
     * Total
     */
    total: number;
    /**
     * Avg Length
     */
    avg_length: number;
    /**
     * Min Length
     */
    min_length: number;
    /**
     * Max Length
     */
    max_length: number;
};

/**
 * DocumentListResponse
 */
export type DocumentListResponse = {
    /**
     * Items
     */
    items: Array<DocumentRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * DocumentPermissionTagsUpdate
 *
 * admin 改文档可见性标签的请求体。
 */
export type DocumentPermissionTagsUpdate = {
    /**
     * Permission Tags
     */
    permission_tags?: Array<string>;
};

/**
 * DocumentRead
 */
export type DocumentRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * File Hash
     */
    file_hash: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size
     */
    size: number;
    /**
     * Status
     */
    status: 'uploading' | 'parsing' | 'indexing' | 'ready' | 'failed';
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Version
     */
    version?: number;
    latest_task?: IngestionTaskRead | null;
    /**
     * Permission Tags
     */
    permission_tags?: Array<string>;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * EvaluationItemPage
 */
export type EvaluationItemPage = {
    /**
     * Items
     */
    items: Array<EvaluationItemRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * EvaluationItemRead
 *
 * 单条 case 的输入快照 + 实际输出 + 指标 + Bad Case 归因。
 */
export type EvaluationItemRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Case Id
     */
    case_id: string;
    /**
     * Question
     */
    question: string;
    /**
     * Expected Answer
     */
    expected_answer: string;
    /**
     * Expected Document Names
     */
    expected_document_names?: Array<string>;
    /**
     * Expected Keywords
     */
    expected_keywords?: Array<string>;
    /**
     * Should Refuse
     */
    should_refuse: boolean;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Actual Answer
     */
    actual_answer: string;
    /**
     * Actual Refused
     */
    actual_refused: boolean;
    /**
     * Citations
     */
    citations?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Retrieved Chunks Meta
     */
    retrieved_chunks_meta?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Query Route
     */
    query_route?: {
        [key: string]: unknown;
    } | null;
    /**
     * Agent Steps
     */
    agent_steps?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Verify Result
     */
    verify_result?: {
        [key: string]: unknown;
    } | null;
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Latency Ms
     */
    latency_ms: number;
    /**
     * First Token Latency Ms
     */
    first_token_latency_ms?: number | null;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Faithfulness
     */
    faithfulness?: number | null;
    /**
     * Answer Relevancy
     */
    answer_relevancy?: number | null;
    /**
     * Context Precision
     */
    context_precision?: number | null;
    /**
     * Context Recall
     */
    context_recall?: number | null;
    /**
     * Citation Hit
     */
    citation_hit?: boolean | null;
    /**
     * Refusal Correct
     */
    refusal_correct: boolean;
    /**
     * Is Bad Case
     */
    is_bad_case: boolean;
    /**
     * Bad Case Category
     */
    bad_case_category?: 'document_parse_failed' | 'chunk_split_bad' | 'embedding_recall_miss' | 'keyword_recall_miss' | 'rrf_fusion_error' | 'rerank_order_error' | 'context_judge_too_loose' | 'context_judge_too_strict' | 'prompt_constraint_weak' | 'generation_off_context' | 'citation_parse_failed' | 'permission_filter_error' | 'other' | null;
    /**
     * Bad Case Note
     */
    bad_case_note?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * EvaluationItemUpdate
 *
 * 前端覆盖 Bad Case 归因。
 *
 * 传 `is_bad_case=null` 时保持原值；显式传 `is_bad_case=false` 可手动把
 * 误判的 case 标回"非 Bad Case"。
 */
export type EvaluationItemUpdate = {
    /**
     * Bad Case Category
     */
    bad_case_category?: 'document_parse_failed' | 'chunk_split_bad' | 'embedding_recall_miss' | 'keyword_recall_miss' | 'rrf_fusion_error' | 'rerank_order_error' | 'context_judge_too_loose' | 'context_judge_too_strict' | 'prompt_constraint_weak' | 'generation_off_context' | 'citation_parse_failed' | 'permission_filter_error' | 'other' | null;
    /**
     * Bad Case Note
     */
    bad_case_note?: string | null;
    /**
     * Is Bad Case
     */
    is_bad_case?: boolean | null;
};

/**
 * EvaluationRunCreate
 *
 * 创建 run 的请求体。dataset_name 不带后缀（如 `seed`）。
 */
export type EvaluationRunCreate = {
    /**
     * Name
     *
     * 便于回看的 run 名称
     */
    name: string;
    /**
     * Dataset Name
     *
     * 评测集文件名（不带 .jsonl）
     */
    dataset_name: string;
};

/**
 * EvaluationRunListItem
 *
 * 列表元素：与 Read 一致字段，提取出来后续可裁字段也方便。
 */
export type EvaluationRunListItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Dataset Name
     */
    dataset_name: string;
    /**
     * Dataset Size
     */
    dataset_size: number;
    /**
     * Status
     */
    status: 'running' | 'completed' | 'failed';
    /**
     * Progress Total
     */
    progress_total: number;
    /**
     * Progress Completed
     */
    progress_completed: number;
    /**
     * Progress Failed
     */
    progress_failed: number;
    /**
     * Faithfulness
     */
    faithfulness?: number | null;
    /**
     * Answer Relevancy
     */
    answer_relevancy?: number | null;
    /**
     * Context Precision
     */
    context_precision?: number | null;
    /**
     * Context Recall
     */
    context_recall?: number | null;
    /**
     * Citation Hit Rate
     */
    citation_hit_rate?: number | null;
    /**
     * Refusal Accuracy
     */
    refusal_accuracy?: number | null;
    /**
     * Avg Latency Ms
     */
    avg_latency_ms?: number | null;
    /**
     * Avg First Token Latency Ms
     */
    avg_first_token_latency_ms?: number | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * EvaluationRunPage
 */
export type EvaluationRunPage = {
    /**
     * Items
     */
    items: Array<EvaluationRunListItem>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * EvaluationRunRead
 */
export type EvaluationRunRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Dataset Name
     */
    dataset_name: string;
    /**
     * Dataset Size
     */
    dataset_size: number;
    /**
     * Status
     */
    status: 'running' | 'completed' | 'failed';
    /**
     * Progress Total
     */
    progress_total: number;
    /**
     * Progress Completed
     */
    progress_completed: number;
    /**
     * Progress Failed
     */
    progress_failed: number;
    /**
     * Faithfulness
     */
    faithfulness?: number | null;
    /**
     * Answer Relevancy
     */
    answer_relevancy?: number | null;
    /**
     * Context Precision
     */
    context_precision?: number | null;
    /**
     * Context Recall
     */
    context_recall?: number | null;
    /**
     * Citation Hit Rate
     */
    citation_hit_rate?: number | null;
    /**
     * Refusal Accuracy
     */
    refusal_accuracy?: number | null;
    /**
     * Avg Latency Ms
     */
    avg_latency_ms?: number | null;
    /**
     * Avg First Token Latency Ms
     */
    avg_first_token_latency_ms?: number | null;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 */
export type HealthStatus = {
    /**
     * Status
     */
    status: 'ok' | 'error' | 'not_configured';
    /**
     * Detail
     */
    detail?: string | null;
};

/**
 * IngestionTaskRead
 *
 * 单条入库任务快照（详情页「最近一次任务」卡片用）。
 */
export type IngestionTaskRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Task Type
     */
    task_type: 'ingest' | 'reindex';
    /**
     * Status
     */
    status: 'pending' | 'running' | 'success' | 'failed';
    /**
     * Retry Count
     */
    retry_count: number;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Progress Total
     */
    progress_total: number;
    /**
     * Progress Done
     */
    progress_done: number;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: 'bearer';
    user: UserRead;
    /**
     * Permission Tags
     */
    permission_tags?: Array<string>;
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * MeResponse
 *
 * 当前登录用户视图：用户基础信息 + 合并后的有效权限标签 + 是否管理员。
 */
export type MeResponse = {
    user: UserRead;
    /**
     * Permission Tags
     */
    permission_tags?: Array<string>;
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * MessageRead
 */
export type MessageRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Citations
     */
    citations?: Array<CitationRead>;
    query_route?: QueryRouteRead | null;
    /**
     * Agent Steps
     */
    agent_steps?: Array<AgentStep> | null;
    verify_result?: VerifyResultRead | null;
    /**
     * Trace Id
     */
    trace_id?: string | null;
    /**
     * Trace Url
     */
    trace_url?: string | null;
    /**
     * Cache Hit
     */
    cache_hit?: boolean;
};

/**
 * QueryRouteRead
 */
export type QueryRouteRead = {
    /**
     * Route
     */
    route: 'original' | 'rewrite' | 'hyde' | 'multi_query';
    /**
     * Query
     */
    query: string;
    /**
     * Rewritten Query
     */
    rewritten_query: string | null;
    /**
     * Hyde Answer
     */
    hyde_answer: string | null;
    /**
     * Multi Queries
     */
    multi_queries: Array<string> | null;
};

/**
 * RetrievalMeta
 *
 * 混合检索调试元数据。
 *
 * - sources：该 chunk 命中的检索路（vector / keyword），两路都命中即"混合"
 * - *_rank：在该路召回结果中的名次（从 1 开始），用于复盘排序
 * - vector_score：cosine similarity，绝对值有意义，做拒答阈值用
 * - keyword_score：ts_rank，相对值，跨 query 不可比
 * - rrf_score：两路融合分，仅在同一次检索内可比
 */
export type RetrievalMeta = {
    /**
     * Sources
     */
    sources?: Array<string>;
    /**
     * Vector Rank
     */
    vector_rank?: number | null;
    /**
     * Keyword Rank
     */
    keyword_rank?: number | null;
    /**
     * Vector Score
     */
    vector_score?: number | null;
    /**
     * Keyword Score
     */
    keyword_score?: number | null;
    /**
     * Rrf Score
     */
    rrf_score?: number | null;
    /**
     * Rerank Score
     */
    rerank_score?: number | null;
};

/**
 * RoleCreate
 */
export type RoleCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Permission Tags
     */
    permission_tags?: Array<string>;
};

/**
 * RoleRead
 */
export type RoleRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Permission Tags
     */
    permission_tags?: Array<string>;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * RoleUpdate
 *
 * name 字段刻意不暴露：策略代码以角色名为锚（"admin"），不允许改名。
 */
export type RoleUpdate = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Permission Tags
     */
    permission_tags?: Array<string> | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Role Ids
     */
    role_ids?: Array<string>;
};

/**
 * UserPage
 */
export type UserPage = {
    /**
     * Items
     */
    items: Array<UserRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Page Size
     */
    page_size: number;
};

/**
 * UserRead
 *
 * 用户响应。role 列表里只展示必要字段，权限标签由前端从 roles 推。
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Status
     */
    status: 'active' | 'disabled';
    /**
     * Roles
     */
    roles?: Array<RoleRead>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserUpdate
 *
 * PATCH 请求体；字段均可选。
 *
 * password 字段如果传非空字符串则重置密码；传 None 不动密码。
 */
export type UserUpdate = {
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Status
     */
    status?: 'active' | 'disabled' | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VerifyResultRead
 *
 * answer_verifier 校验结果，落库到 messages.extra_metadata.verify_result。
 *
 * - verified=True：答案被引用片段支撑；reason 通常为空
 * - verified=False：触发拒答替换（service 层覆盖 answer/refused），reason 写入失败原因
 */
export type VerifyResultRead = {
    /**
     * Verified
     */
    verified: boolean;
    /**
     * Reason
     */
    reason: string | null;
};

export type HealthAppData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthAppResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type HealthAppResponse = HealthAppResponses[keyof HealthAppResponses];

export type HealthDbData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/db';
};

export type HealthDbResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type HealthDbResponse = HealthDbResponses[keyof HealthDbResponses];

export type HealthCosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health/cos';
};

export type HealthCosResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type HealthCosResponse = HealthCosResponses[keyof HealthCosResponses];

export type ListDocumentsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Status
         *
         * 按文档状态筛选
         */
        status?: 'uploading' | 'parsing' | 'indexing' | 'ready' | 'failed' | null;
    };
    url: '/api/documents';
};

export type ListDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsError = ListDocumentsErrors[keyof ListDocumentsErrors];

export type ListDocumentsResponses = {
    /**
     * Successful Response
     */
    200: DocumentListResponse;
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type UploadDocumentData = {
    body: BodyUploadDocument;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/documents';
};

export type UploadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentError = UploadDocumentErrors[keyof UploadDocumentErrors];

export type UploadDocumentResponses = {
    /**
     * Successful Response
     */
    201: DocumentRead;
};

export type UploadDocumentResponse = UploadDocumentResponses[keyof UploadDocumentResponses];

export type DeleteDocumentData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/documents/{document_id}';
};

export type DeleteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDocumentError = DeleteDocumentErrors[keyof DeleteDocumentErrors];

export type DeleteDocumentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDocumentResponse = DeleteDocumentResponses[keyof DeleteDocumentResponses];

export type GetDocumentData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/documents/{document_id}';
};

export type GetDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentError = GetDocumentErrors[keyof GetDocumentErrors];

export type GetDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentRead;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];

export type RetryDocumentData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/documents/{document_id}/retry';
};

export type RetryDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryDocumentError = RetryDocumentErrors[keyof RetryDocumentErrors];

export type RetryDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentRead;
};

export type RetryDocumentResponse = RetryDocumentResponses[keyof RetryDocumentResponses];

export type DownloadDocumentData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: {
        /**
         * Download
         *
         * 1=强制下载, 0=尝试内联预览
         */
        download?: number;
        /**
         * Token
         *
         * Bearer token（iframe/新窗口无法带 header 时使用）
         */
        token?: string | null;
    };
    url: '/api/documents/{document_id}/file';
};

export type DownloadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DownloadDocumentError = DownloadDocumentErrors[keyof DownloadDocumentErrors];

export type DownloadDocumentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListDocumentChunksData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/documents/{document_id}/chunks';
};

export type ListDocumentChunksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentChunksError = ListDocumentChunksErrors[keyof ListDocumentChunksErrors];

export type ListDocumentChunksResponses = {
    /**
     * Successful Response
     */
    200: DocumentChunkListResponse;
};

export type ListDocumentChunksResponse = ListDocumentChunksResponses[keyof ListDocumentChunksResponses];

export type GetDocumentChunkData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Document Id
         */
        document_id: string;
        /**
         * Chunk Id
         */
        chunk_id: string;
    };
    query?: never;
    url: '/api/documents/{document_id}/chunks/{chunk_id}';
};

export type GetDocumentChunkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentChunkError = GetDocumentChunkErrors[keyof GetDocumentChunkErrors];

export type GetDocumentChunkResponses = {
    /**
     * Successful Response
     */
    200: DocumentChunkDetail;
};

export type GetDocumentChunkResponse = GetDocumentChunkResponses[keyof GetDocumentChunkResponses];

export type UpdateDocumentPermissionTagsData = {
    body: DocumentPermissionTagsUpdate;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/documents/{document_id}/permission-tags';
};

export type UpdateDocumentPermissionTagsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDocumentPermissionTagsError = UpdateDocumentPermissionTagsErrors[keyof UpdateDocumentPermissionTagsErrors];

export type UpdateDocumentPermissionTagsResponses = {
    /**
     * Successful Response
     */
    200: DocumentRead;
};

export type UpdateDocumentPermissionTagsResponse = UpdateDocumentPermissionTagsResponses[keyof UpdateDocumentPermissionTagsResponses];

export type ReindexDocumentData = {
    body: BodyReindexDocument;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/documents/{document_id}/reindex';
};

export type ReindexDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReindexDocumentError = ReindexDocumentErrors[keyof ReindexDocumentErrors];

export type ReindexDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentRead;
};

export type ReindexDocumentResponse = ReindexDocumentResponses[keyof ReindexDocumentResponses];

export type ListConversationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/conversations';
};

export type ListConversationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListConversationsError = ListConversationsErrors[keyof ListConversationsErrors];

export type ListConversationsResponses = {
    /**
     * Successful Response
     */
    200: ConversationPage;
};

export type ListConversationsResponse = ListConversationsResponses[keyof ListConversationsResponses];

export type CreateConversationData = {
    body: ConversationCreate;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/conversations';
};

export type CreateConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateConversationError = CreateConversationErrors[keyof CreateConversationErrors];

export type CreateConversationResponses = {
    /**
     * Successful Response
     */
    201: ConversationRead;
};

export type CreateConversationResponse = CreateConversationResponses[keyof CreateConversationResponses];

export type DeleteConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}';
};

export type DeleteConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationError = DeleteConversationErrors[keyof DeleteConversationErrors];

export type DeleteConversationResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteConversationResponse = DeleteConversationResponses[keyof DeleteConversationResponses];

export type GetConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}';
};

export type GetConversationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationError = GetConversationErrors[keyof GetConversationErrors];

export type GetConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationDetail;
};

export type GetConversationResponse = GetConversationResponses[keyof GetConversationResponses];

export type StreamChatData = {
    body: ChatRequest;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/conversations/{conversation_id}/chat';
};

export type StreamChatErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamChatError = StreamChatErrors[keyof StreamChatErrors];

export type StreamChatResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListEvaluationDatasetsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/evaluations/datasets';
};

export type ListEvaluationDatasetsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEvaluationDatasetsError = ListEvaluationDatasetsErrors[keyof ListEvaluationDatasetsErrors];

export type ListEvaluationDatasetsResponses = {
    /**
     * Successful Response
     */
    200: DatasetListResponse;
};

export type ListEvaluationDatasetsResponse = ListEvaluationDatasetsResponses[keyof ListEvaluationDatasetsResponses];

export type ListEvaluationRunsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/evaluations/runs';
};

export type ListEvaluationRunsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEvaluationRunsError = ListEvaluationRunsErrors[keyof ListEvaluationRunsErrors];

export type ListEvaluationRunsResponses = {
    /**
     * Successful Response
     */
    200: EvaluationRunPage;
};

export type ListEvaluationRunsResponse = ListEvaluationRunsResponses[keyof ListEvaluationRunsResponses];

export type CreateEvaluationRunData = {
    body: EvaluationRunCreate;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/evaluations/runs';
};

export type CreateEvaluationRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEvaluationRunError = CreateEvaluationRunErrors[keyof CreateEvaluationRunErrors];

export type CreateEvaluationRunResponses = {
    /**
     * Successful Response
     */
    201: EvaluationRunRead;
};

export type CreateEvaluationRunResponse = CreateEvaluationRunResponses[keyof CreateEvaluationRunResponses];

export type DeleteEvaluationRunData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/evaluations/runs/{run_id}';
};

export type DeleteEvaluationRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEvaluationRunError = DeleteEvaluationRunErrors[keyof DeleteEvaluationRunErrors];

export type DeleteEvaluationRunResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteEvaluationRunResponse = DeleteEvaluationRunResponses[keyof DeleteEvaluationRunResponses];

export type GetEvaluationRunData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/evaluations/runs/{run_id}';
};

export type GetEvaluationRunErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEvaluationRunError = GetEvaluationRunErrors[keyof GetEvaluationRunErrors];

export type GetEvaluationRunResponses = {
    /**
     * Successful Response
     */
    200: EvaluationRunRead;
};

export type GetEvaluationRunResponse = GetEvaluationRunResponses[keyof GetEvaluationRunResponses];

export type ListEvaluationItemsData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
        /**
         * Bad Case Only
         */
        bad_case_only?: boolean;
        /**
         * Category
         */
        category?: 'document_parse_failed' | 'chunk_split_bad' | 'embedding_recall_miss' | 'keyword_recall_miss' | 'rrf_fusion_error' | 'rerank_order_error' | 'context_judge_too_loose' | 'context_judge_too_strict' | 'prompt_constraint_weak' | 'generation_off_context' | 'citation_parse_failed' | 'permission_filter_error' | 'other' | null;
    };
    url: '/api/evaluations/runs/{run_id}/items';
};

export type ListEvaluationItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEvaluationItemsError = ListEvaluationItemsErrors[keyof ListEvaluationItemsErrors];

export type ListEvaluationItemsResponses = {
    /**
     * Successful Response
     */
    200: EvaluationItemPage;
};

export type ListEvaluationItemsResponse = ListEvaluationItemsResponses[keyof ListEvaluationItemsResponses];

export type GetEvaluationItemData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/evaluations/items/{item_id}';
};

export type GetEvaluationItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEvaluationItemError = GetEvaluationItemErrors[keyof GetEvaluationItemErrors];

export type GetEvaluationItemResponses = {
    /**
     * Successful Response
     */
    200: EvaluationItemRead;
};

export type GetEvaluationItemResponse = GetEvaluationItemResponses[keyof GetEvaluationItemResponses];

export type UpdateEvaluationItemData = {
    body: EvaluationItemUpdate;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Item Id
         */
        item_id: string;
    };
    query?: never;
    url: '/api/evaluations/items/{item_id}';
};

export type UpdateEvaluationItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEvaluationItemError = UpdateEvaluationItemErrors[keyof UpdateEvaluationItemErrors];

export type UpdateEvaluationItemResponses = {
    /**
     * Successful Response
     */
    200: EvaluationItemRead;
};

export type UpdateEvaluationItemResponse = UpdateEvaluationItemResponses[keyof UpdateEvaluationItemResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type GetCurrentUserData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetCurrentUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type ListUsersData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Page Size
         */
        page_size?: number;
    };
    url: '/api/users';
};

export type ListUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * Successful Response
     */
    200: UserPage;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/users';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type UpdateUserData = {
    body: UserUpdate;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type UpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type AssignUserRolesData = {
    body: AssignRolesRequest;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}/roles';
};

export type AssignUserRolesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignUserRolesError = AssignUserRolesErrors[keyof AssignUserRolesErrors];

export type AssignUserRolesResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type AssignUserRolesResponse = AssignUserRolesResponses[keyof AssignUserRolesResponses];

export type ListRolesData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/roles';
};

export type ListRolesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRolesError = ListRolesErrors[keyof ListRolesErrors];

export type ListRolesResponses = {
    /**
     * Response Listroles
     *
     * Successful Response
     */
    200: Array<RoleRead>;
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type CreateRoleData = {
    body: RoleCreate;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/roles';
};

export type CreateRoleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateRoleError = CreateRoleErrors[keyof CreateRoleErrors];

export type CreateRoleResponses = {
    /**
     * Successful Response
     */
    201: RoleRead;
};

export type CreateRoleResponse = CreateRoleResponses[keyof CreateRoleResponses];

export type DeleteRoleData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}';
};

export type DeleteRoleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRoleError = DeleteRoleErrors[keyof DeleteRoleErrors];

export type DeleteRoleResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteRoleResponse = DeleteRoleResponses[keyof DeleteRoleResponses];

export type UpdateRoleData = {
    body: RoleUpdate;
    headers?: {
        /**
         * Authorization
         */
        Authorization?: string | null;
    };
    path: {
        /**
         * Role Id
         */
        role_id: string;
    };
    query?: never;
    url: '/api/roles/{role_id}';
};

export type UpdateRoleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRoleError = UpdateRoleErrors[keyof UpdateRoleErrors];

export type UpdateRoleResponses = {
    /**
     * Successful Response
     */
    200: RoleRead;
};

export type UpdateRoleResponse = UpdateRoleResponses[keyof UpdateRoleResponses];
