"""add ingestion_tasks table and document version

Revision ID: d71e523b56af
Revises: 80b24fa891b0
Create Date: 2026-08-10 22:59:39.647293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71e523b56af'
down_revision: Union[str, Sequence[str], None] = '80b24fa891b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_done', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_tasks_document_id'), 'ingestion_tasks', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.create_index(
        "ix_ingestion_tasks_document_created",
        "ingestion_tasks",
        ["document_id", sa.text("created_at DESC")],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_permission_tags'), 'documents', ['permission_tags'], unique=False, postgresql_using='gin')
    op.drop_column('documents', 'version')
    op.drop_index(op.f('ix_ingestion_tasks_document_id'), table_name='ingestion_tasks')
    op.drop_table('ingestion_tasks')
    # ### end Alembic commands ###

